apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medicore-ingress
  namespace: medicore
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - medicore.example.com
    - prometheus.medicore.example.com
    secretName: medicore-tls
  rules:
  - host: medicore.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 3000
  - host: prometheus.medicore.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
